# Generated by Django 4.2.3 on 2023-07-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='borrower_loan',
        ),
    ]
