# Generated by Django 4.2.3 on 2023-07-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_loan_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='penor_pinjaman',
            new_name='tenor_pinjaman',
        ),
    ]
