# Generated by Django 4.2.3 on 2023-07-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_penor_pinjaman_loan_tenor_pinjaman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='anggal_publish',
            new_name='tanggal_publish',
        ),
    ]
