# Generated by Django 4.2.3 on 2023-07-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_invoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='borrower_loan_invoice',
        ),
    ]
