# Generated by Django 4.2.3 on 2023-07-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_invoice_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='principal_amout',
            new_name='principal_amount',
        ),
    ]
