# Generated by Django 4.2.3 on 2023-07-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'compensation',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('compensation', models.ManyToManyField(related_name='employee_compensation', to='home.compensation')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_contact', to='home.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
