# Generated by Django 4.2.3 on 2023-07-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_compensation_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
