# Generated by Django 4.2.3 on 2023-07-28 01:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=55)),
                ('location', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_event', to='home.employee')),
            ],
            options={
                'db_table': 'employee_event',
            },
        ),
    ]
